#pragma once

// MyFile
#include"DirectXUtilityModule/DirectXDataTypes.h"

// SamplerFilterType
enum class SamplerFilterType {
	Point															= D3D11_FILTER_MIN_MAG_MIP_POINT,
	MIN_MAG_POINT_MIP_LINEAR								= D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR,
	MIN_POINT_MAG_LINEAR_MIP_POINT						= D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT,
	MIN_POINT_MAG_MIP_LINEAR								= D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR,
	MIN_LINEAR_MAG_MIP_POINT								= D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT,
	MIN_LINEAR_MAG_POINT_MIP_LINEAR						= D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR,
	MIN_MAG_LINEAR_MIP_POINT								= D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT,
	Linear														= D3D11_FILTER_MIN_MAG_MIP_LINEAR,
	ANISOTROPIC													= D3D11_FILTER_ANISOTROPIC,
	COMPARISON_MIN_MAG_MIP_POINT							= D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT,
	COMPARISON_MIN_MAG_POINT_MIP_LINEAR					= D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR,
	COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT			= D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT,
	COMPARISON_MIN_POINT_MAG_MIP_LINEAR					= D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR,
	COMPARISON_MIN_LINEAR_MAG_MIP_POINT					= D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT,
	COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR		= D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR,
	COMPARISON_MIN_MAG_LINEAR_MIP_POINT					= D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT,
	COMPARISON_MIN_MAG_MIP_LINEAR							= D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR,
	COMPARISON_ANISOTROPIC									= D3D11_FILTER_COMPARISON_ANISOTROPIC,
};